name: publish

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract Versions for All Modules
        id: extract_versions
        run: |
          for module in $(find . -maxdepth 1 -type d | grep -v '^\.$' | grep -v buildSrc); do
            if [ -f "$module/gradle.properties" ]; then
              VERSION=$(awk -F '=' '/^version/ {print $2}' "$module/gradle.properties")
              echo "${module}_VERSION=${VERSION}" >> $GITHUB_ENV
            else
              echo "No gradle.properties found in $module. Skipping..."
            fi
          done

      - name: Publish packages for all modules
        run: |
          for module in $(find . -maxdepth 1 -type d | grep -v '^\.$' | grep -v buildSrc); do
            if [ -f "$module/gradle.properties" ]; then
              VERSION_VAR_NAME="${module}_VERSION"
              VERSION=${!VERSION_VAR_NAME}
              ./gradlew :$module:publish -Pversion=$VERSION -Pgpr.user=${{ github.actor }} -Pgpr.key=${{ secrets.GITHUB_TOKEN }}
            fi
          done
